// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnNXaRelAwtmRbrhT5BA2gu1UcRr2H7N8',
    appId: '1:717547327403:web:b91b54f093f2184f354cee',
    messagingSenderId: '717547327403',
    projectId: 'dimsum-app',
    authDomain: 'dimsum-app.firebaseapp.com',
    storageBucket: 'dimsum-app.firebasestorage.app',
    measurementId: 'G-8EWGJRGNK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsokeMj22OtgxeHVfkaqyGRzVjtAZ_ges',
    appId: '1:717547327403:android:99f039b9793afb16354cee',
    messagingSenderId: '717547327403',
    projectId: 'dimsum-app',
    storageBucket: 'dimsum-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2FNQJoACHXyWC-lv-P8ntSyH7LPNoT1c',
    appId: '1:717547327403:ios:752c5a113f6d9bd2354cee',
    messagingSenderId: '717547327403',
    projectId: 'dimsum-app',
    storageBucket: 'dimsum-app.firebasestorage.app',
    iosBundleId: 'com.example.dimsumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2FNQJoACHXyWC-lv-P8ntSyH7LPNoT1c',
    appId: '1:717547327403:ios:752c5a113f6d9bd2354cee',
    messagingSenderId: '717547327403',
    projectId: 'dimsum-app',
    storageBucket: 'dimsum-app.firebasestorage.app',
    iosBundleId: 'com.example.dimsumApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnNXaRelAwtmRbrhT5BA2gu1UcRr2H7N8',
    appId: '1:717547327403:web:9477ef29471b005c354cee',
    messagingSenderId: '717547327403',
    projectId: 'dimsum-app',
    authDomain: 'dimsum-app.firebaseapp.com',
    storageBucket: 'dimsum-app.firebasestorage.app',
    measurementId: 'G-LCCHSHLP3Q',
  );
}
